apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ss-md-hack.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ss-md-hack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Application config can be added here
  # Currently all config is via environment variables
