apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ss-md-hack.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "ss-md-hack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ include "ss-md-hack.databaseUrl" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ss-md-hack.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "ss-md-hack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ include "ss-md-hack.redisUrl" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ss-md-hack.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "ss-md-hack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password-hash: {{ .Values.admin.passwordHash }}
